# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: solarguard.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'solarguard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10solarguard.proto\x12\nsolarguard\"1\n\x0fImagenSolicitud\x12\x0e\n\x06imagen\x18\x01 \x01(\x0c\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"\x07\n\x05Vacio\"\x8a\x01\n\x16ResultadoClasificacion\x12\x11\n\tcondicion\x18\x01 \x01(\t\x12\x11\n\tconfianza\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x11\n\tprioridad\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63\x63ion\x18\x05 \x01(\t\x12\x12\n\nfecha_hora\x18\x06 \x01(\t\"!\n\x0e\x45stadoServicio\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2\xad\x01\n\x12SolarGuardServicio\x12S\n\x10\x43lasificarImagen\x12\x1b.solarguard.ImagenSolicitud\x1a\".solarguard.ResultadoClasificacion\x12\x42\n\x11VerificarServicio\x12\x11.solarguard.Vacio\x1a\x1a.solarguard.EstadoServiciob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solarguard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGENSOLICITUD']._serialized_start=32
  _globals['_IMAGENSOLICITUD']._serialized_end=81
  _globals['_VACIO']._serialized_start=83
  _globals['_VACIO']._serialized_end=90
  _globals['_RESULTADOCLASIFICACION']._serialized_start=93
  _globals['_RESULTADOCLASIFICACION']._serialized_end=231
  _globals['_ESTADOSERVICIO']._serialized_start=233
  _globals['_ESTADOSERVICIO']._serialized_end=266
  _globals['_SOLARGUARDSERVICIO']._serialized_start=269
  _globals['_SOLARGUARDSERVICIO']._serialized_end=442
# @@protoc_insertion_point(module_scope)
