# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import solarguard_pb2 as solarguard__pb2

GRPC_GENERATED_VERSION = "1.83.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in solarguard_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SolarGuardServicioStub:
    """---------------------------------------------------------------------------
    El servicio que expone el backend.

    Literalmente es una lista de funciones remotas: la interfaz las llama
    como si fueran funciones normales, pero en realidad la peticion viaja
    por la red hasta el servidor que hace el trabajo pesado (clasificar).
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClasificarImagen = channel.unary_unary(
            "/solarguard.SolarGuardServicio/ClasificarImagen",
            request_serializer=solarguard__pb2.ImagenSolicitud.SerializeToString,
            response_deserializer=solarguard__pb2.ResultadoClasificacion.FromString,
            _registered_method=True,
        )
        self.VerificarServicio = channel.unary_unary(
            "/solarguard.SolarGuardServicio/VerificarServicio",
            request_serializer=solarguard__pb2.Vacio.SerializeToString,
            response_deserializer=solarguard__pb2.EstadoServicio.FromString,
            _registered_method=True,
        )


class SolarGuardServicioServicer:
    """---------------------------------------------------------------------------
    El servicio que expone el backend.

    Literalmente es una lista de funciones remotas: la interfaz las llama
    como si fueran funciones normales, pero en realidad la peticion viaja
    por la red hasta el servidor que hace el trabajo pesado (clasificar).
    ---------------------------------------------------------------------------
    """

    def ClasificarImagen(self, request, context):
        """Clasifica una imagen de panel solar y devuelve el ticket de mantenimiento."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def VerificarServicio(self, request, context):
        """Verifica que el servidor este activo. Sirve para que la interfaz
        avise al usuario cuando el backend no esta corriendo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SolarGuardServicioServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ClasificarImagen": grpc.unary_unary_rpc_method_handler(
            servicer.ClasificarImagen,
            request_deserializer=solarguard__pb2.ImagenSolicitud.FromString,
            response_serializer=solarguard__pb2.ResultadoClasificacion.SerializeToString,
        ),
        "VerificarServicio": grpc.unary_unary_rpc_method_handler(
            servicer.VerificarServicio,
            request_deserializer=solarguard__pb2.Vacio.FromString,
            response_serializer=solarguard__pb2.EstadoServicio.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "solarguard.SolarGuardServicio", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "solarguard.SolarGuardServicio", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SolarGuardServicio:
    """---------------------------------------------------------------------------
    El servicio que expone el backend.

    Literalmente es una lista de funciones remotas: la interfaz las llama
    como si fueran funciones normales, pero en realidad la peticion viaja
    por la red hasta el servidor que hace el trabajo pesado (clasificar).
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def ClasificarImagen(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/solarguard.SolarGuardServicio/ClasificarImagen",
            solarguard__pb2.ImagenSolicitud.SerializeToString,
            solarguard__pb2.ResultadoClasificacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def VerificarServicio(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/solarguard.SolarGuardServicio/VerificarServicio",
            solarguard__pb2.Vacio.SerializeToString,
            solarguard__pb2.EstadoServicio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
